Сборка проекта
js-tasks-ru/jsbasic-20220211_mks pull request #10
Opened 2022-04-06 14:04 UTC by majorof

1. Добавил preventDefault в 7.1, чтобы страница не дергалась при кликах на элементы фильтра
2. Поправил 7.4 для автоматического расчета дефолтных значений слайдера
3. Собрал проект

2022-04-08 07:30 UTC, SinimaWath commented
у тебя есть конфликт в первой и второй задаче. Поправь плиз

2022-04-08 07:33 UTC, SinimaWath requested changes

2022-04-08 07:33 UTC, SinimaWath commented on 9-module/2-task/index.js
> +    await responsePromise
Если используешь then - то тебе обычно не нужен await. и наоборот.

На async/await-ах, можно переписать вот так:
```
const resp = await fetch('...');
const json = await resp.json();
```

Или на промисах вот так:
```
return responsePromise.then().then().catch();
```

2022-04-08 09:39 UTC, majorof commented on 9-module/2-task/index.js
> +    await responsePromise
Здесь я использовал await вот почему:

Также нужно не забыть сделать await получения товаров, ведь метод render возвращает промис.

2022-04-08 09:47 UTC, majorof commented
> у тебя есть конфликт в первой и второй задаче. Поправь плиз

не понимаю, что нужно сделать, в консоли все ок

2022-04-08 18:53 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-08 19:27 UTC, SinimaWath approved these changes

2022-04-08 19:27 UTC, merged

2022-04-09 09:18 UTC, majorof commented on 9-module/2-task/index.js
> +    await responsePromise
Ответь тут еще плз