Занятие 7. Задачи 1, 2, 3, 4.
js-tasks-ru/jsbasic-20220211_mks pull request #9
Opened 2022-03-24 14:15 UTC by majorof

Не могу пройти тесты в задаче 7.2. Подскажите плз

2022-03-24 16:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-03-25 13:04 UTC, SinimaWath requested changes

2022-03-25 13:04 UTC, SinimaWath commented on 7-module/1-task/index.js
> +      innerMenu.addEventListener('scroll', () => {
Каждый клик на стрелки, будет создавать новый обработчик события. 

Причем этот обработчик события не будет удаляться. 

Поэтому попробуй сделать один обработчик, во время рендера

2022-03-25 13:04 UTC, SinimaWath commented on 7-module/1-task/index.js
> +      });
Нет необходимости вешать 2 обработчика события, давай один

2022-03-25 13:04 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    }
Тут нет необходимости выносить в отдельную функцию, так как она используется только один раз

2022-03-25 13:04 UTC, SinimaWath commented on 7-module/2-task/index.js
> +      this.elem.remove();
у тебя такой же код в методе close, можно вызвать его

2022-03-26 19:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-03 14:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-03 18:07 UTC, SinimaWath requested changes

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    document.querySelector('.products-grid').innerHTML = '';
В компонентах нельзя оперировать с document.

А вдруг в DOM вставили еще один `.products-grid`, чтобы не было конфликтов, используй: `this.elem`, котоырй ссылается именно на нужный тебе DOM елемент

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/3-task/index.js
> +        }
Слишком сложно и немного не надежно.

По-условию задачи у продуктов есть id, чтобы найти совпадения надо именно его и использовать: `product.id`

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    }
Для просты, давай используем стрелочную функцию:
```
this.cartItems = this.cartItems.map(() => {
   ....
});
```

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    if (this.cartItems.length > 0) {
Те же замечания что и к коду в 8-3

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    }
Для удаления модального окна, есть метод класса Modal.

давай его исопльзовать

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/4-task/index.js
> +      let modalBody = document.querySelector('.modal');
А если в DOM есть другие modal? Тут тоже надо использовать именно тот DOM елемент, который создан в методе renderModal

2022-04-03 18:07 UTC, SinimaWath commented on 8-module/4-task/index.js
> +            document.querySelector('.modal__body').innerHTML = `
надо использовать метод setBody у класса Modal

2022-04-04 14:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-04 14:36 UTC, majorof commented
Спасибо за правки, на самом деле почти обо всем думал, но почему-то не довел до ума, а сейчас сообразил вынести new Modal в конструктор и сразу легче стало жить )

2022-04-06 13:39 UTC, SinimaWath approved these changes
все ок, круто

2022-04-06 13:40 UTC, merged